### PR TITLE
Unable to build JSDuck gem

### LINKED ISSUE #4: Unable to build JSDuck gem
Following the build instructions:

> 6. `> rake configure`

image

The link to `extjs` library used by `Rakefile` is outdated. Looks like Sencha does not provide the download anymore. I was able to overcome the issue using some 3rd party url like:

```
# Download ExtJS into template/extjs
task :get_extjs do
  system "curl -o template/extjs.zip https://ext4all.com/ext/download/ext-4.1.1-gpl.zip"
  system "unzip template/extjs.zip -d template/"
  system "rm -rf template/extjs"
  system "mv template/extjs-4.1.1 template/extjs"
  system "rm template/extjs.zip"
end
```

Then this step seems to be working fine properly downloading and extracting `ExtJS` library, however next step fails:

> 7. `> rake ext4`

image

### PR DESCRIPTION
**Pull request by f1ames**
There were few problems here:

* Outdated ExtJS 4 link in [`get_extjs`](https://github.com/ckeditor/jsduck/compare/ckeditor-customizations...ckeditor:t/4?expand=1#diff-52c976fc38ed2b4e3b1192f8a8e24cffR200) (not sure if we should use the unofficial one, but there is no official one AFAIK - maybe we should put it somwhere in this repo?).
* [`-R` flag](https://github.com/ckeditor/jsduck/compare/ckeditor-customizations...ckeditor:t/4?expand=1#diff-52c976fc38ed2b4e3b1192f8a8e24cffR106) should be used on OS X instead of `-r`.
* [Dependencies](https://github.com/ckeditor/jsduck/compare/ckeditor-customizations...ckeditor:t/4?expand=1#diff-04c6e90faac2675aa89e2176d2eec7d8R15) .

---

Closes #4.

### CODE REVIEW

**Comment by f1ames** [comment]
Ohhh, and also [link to Sencha SDK is problematic](https://github.com/ckeditor/jsduck/pull/5/files#diff-04c6e90faac2675aa89e2176d2eec7d8R17) - again is hosted by [someone, somewhere on github](https://github.com/Shereef/Sencha-Touch-2) - maybe we should fork it or add it here (same as with ExtJS build) - I am not only sure if it is okay from legal point of view.

**Review by Comandeer — COMMENTED** [review]
Gem is built, however I have some doubts:

-   I have one error while `rake ext4` and than `rake gem`:

    ```bash
    error template/resources/sass/docs-ext.scss (Line 2 of template/extjs/resources/themes/stylesheets/ext4/default/_all.scss: File to import not found or unreadable: blueprint/typography.
    Load paths:
      Compass::SpriteImporter
      /Users/comandeer/repos/ckeditor/jsduck/template/resources/sass
      /usr/local/lib/ruby/gems/2.4.0/gems/compass-core-1.0.3/stylesheets
      /Users/comandeer/repos/ckeditor/jsduck/template/extjs/resources/themes/stylesheets)
    Compilation failed in 1 files.
    ```

-   I can't install Sencha SDK Tools from given location. They just don't work…

**Comment by f1ames** [comment]
> I have one error while rake ext4 and than rake gem

I had the same issue, are you sure you used proper `compass` and `sass` gem versions (see https://github.com/ckeditor/jsduck/pull/5/files#diff-04c6e90faac2675aa89e2176d2eec7d8R19)? This error is caused by latest `compass` gem which no longer includes `blueprint` library/gem. You have to use `compass 0.12.2`.

> I can't install Sencha SDK Tools from given location. They just don't work…

What do you mean? I was able to use https://github.com/Shereef/Sencha-Touch-2/blob/master/SenchaSDKTools-2.0.0-beta3-osx.app.zip. Make sure you are able to execute `sencha` command in the terminal.

**Comment by Comandeer** [comment]
> are you sure you used proper compass and sass gem versions

I've installed proper version, but I have newer version installed earlier… After uninstalling it, everything worked fine.

> Make sure you are able to execute sencha command in the terminal.

Well, I'm not able, but I don't see why this command is needed? Everything seems to be working fine.

**Comment by f1ames** [comment]
> Well, I'm not able, but I don't see why this command is needed? Everything seems to be working fine.

Sencha lib is used in Rakefile in those two places:
https://github.com/ckeditor/jsduck/blob/stable/Rakefile#L41 https://github.com/ckeditor/jsduck/blob/stable/Rakefile#L106

So it should at last throw `Error: Unable to access jarfile /bin/yuicompressor.jar` when running `rake gem`.

**Comment by Comandeer** [comment]
Ok, after reinstalling Sencha SDK, everything seems to be working now

**Review by Comandeer — APPROVED** [review]

**Pull request merged**
